### ISSUE TITLE
[BUG] Update epoch references in configs while updating a project

### ISSUE THREAD

**Issue by HristiyanG** [aeternity/aepp-aeproject-js#308] opened 2019-12-17 09:07 UTC
While running aeproject init update we should consider updating the old epoch references

**Comment by maptuhec** [comment] 2020-01-23 13:47
The issue is resolved in the latest version of aeproject (2.1.1).  In order to work though, the user must update the all docker files and dependencies.

**Closed by maptuhec** 2020-01-23 13:47 UTC
Labels: aeproject, bug
