### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-aeproject-js#239] opened 2019-10-11 06:16 UTC
Unable to deploy on mainnet, neither on testnet.....
```
➜  waellet-contracts git:(master) ✗ aeproject deploy -n mainnet -s <SECRETKEY>
API ERROR: Error: Unsupported node version 4.2.1. Supported: >= 2.3.0 < 4.0.0
➜  waellet-contracts git:(master) ✗ aeproject deploy -n testnet -s <SECRETKEY>
API ERROR: Error: Unsupported node version 5.0.0-rc.4. Supported: >= 2.3.0 < 4.0.0
```

**Comment by maptuhec** [comment] 2019-10-14 11:39
We have found the issue, and we are working on a new release.

**Comment by alekseytsekov** [comment] 2019-10-16 07:36
Hi @mradkov 
with the latest release you should be able to deploy.
```
aleksey@Aleksey:~/Documents/projects/….$ aeproject deploy -n testnet -s YOUR_SECRET_KEY --compiler https://compiler.aepps.com
===== Contract: ExampleContract.aes has been deployed at ct_zwasjzATmkfLzuAsWJNV5MAW1Ubyg5aY6La2ug3Fjb3qdQV9W =====
Your deployment script finished successfully!
aleksey@Aleksey:~/Documents/projects/...$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
alekseytsekov@Aleksey:~/Documents/projects/...$
```

**Comment by mradkov** [comment] 2019-10-17 11:11
The issue is still present.

```
➜  waellet-contracts git:(master) ✗ aeproject -V     
1.0.2
➜  waellet-contracts git:(master) ✗ aeproject deploy -n testnet -s <SECRET_KEY>
API ERROR: Error: Unsupported node version 5.0.0-rc.4. Supported: >= 2.3.0 < 4.0.0
```

**Comment by maptuhec** [comment] 2019-10-17 11:12
@mradkov did you make **aeproject init --update** in the project folder when you run **aaeproject deploy** ?

Best,
Martin

**Comment by mradkov** [comment] 2019-10-17 11:14
> @mradkov did you make **aeproject init --update** in the project folder when you run **aaeproject deploy** ?
> 
> Best,
> Martin

```
➜  waellet-contracts git:(master) ✗ aeproject init --update
===== Updating AEproject files =====
===== Creating docker directory =====
✔ ./docker-compose.yml already exists.
Do you want to overwrite './docker-compose.yml'? (YES/no): … YES
✔ ./docker already exists.
Do you want to overwrite './docker'? (YES/no): … YES
✔ ./docker-compose.compiler.yml already exists.
Do you want to overwrite './docker-compose.compiler.yml'? (YES/no): … YES
===== Installing AEproject locally =====
===== Installing aepp-sdk =====
===== Installing yarn locally =====
===== AEproject was successfully updated! =====
➜  waellet-contracts git:(master) ✗ aeproject deploy -n testnet -s <SECRET_KEY>
API ERROR: Error: Unsupported node version 5.0.0-rc.4. Supported: >= 2.3.0 < 4.0.0
➜  waellet-contracts git:(master) ✗ 
```

**Comment by maptuhec** [comment] 2019-10-17 11:15
@mradkov can you share the package.json content from your project, or at least the dependencies?

**Comment by mradkov** [comment] 2019-10-17 11:18
Here it is: https://github.com/waellet/waellet-contracts/blob/master/package.json

**Comment by maptuhec** [comment] 2019-10-17 11:27
@mradkov THanks, I will clone the project and I will try to reproduce.

**Comment by alekseytsekov** [comment] 2019-10-29 17:29
Hi @mradkov 

1. remove forgae dependencies from package.json
2. replace forgae-lib with aeproject-lib in deploy.js
3.  fix your contract, current one cannot be compiled
// only for test
```
contract ExampleContract =
   entrypoint main(x : int) = x
```
4. I think it ours bug, you should provide and compiler url too. We will fix this in next release.
4.1  `aeproject deploy -n testnet -s SECRET_KEY --compiler https://latest.compiler.aepps.com`

Best,
Aleksey

**Comment by mradkov** [comment] 2019-10-29 19:58
> Hi @mradkov
> 
> 1. remove forgae dependencies from package.json
> 2. replace forgae-lib with aeproject-lib in deploy.js
> 3. fix your contract, current one cannot be compiled
>    // only for test
> 
> ```
> contract ExampleContract =
>    entrypoint main(x : int) = x
> ```
> 
> 1. I think it ours bug, you should provide and compiler url too. We will fix this in next release.
>    4.1  `aeproject deploy -n testnet -s SECRET_KEY --compiler https://latest.compiler.aepps.com`
> 
> Best,
> Aleksey

Isn't `aeproject init --update` supposed to take care of 1 and 2?

Regarding 3. - the contracts I'm trying to deploy are compiling successfully at https://testnet.contracts.aepps.com

4. I'll try with the `--compiler` now.

**Comment by HristiyanG** [comment] 2019-12-16 14:42
Hey @mradkov ,

Is this issue still ongoing?

**Comment by HristiyanG** [comment] 2020-01-06 14:52
I'm closing this since there has been no reply. If any further issue on this appears we still could reopen the issue.

**Closed** 2020-01-06 14:52 UTC
Labels: aeproject, bug
